os: linux
dist: bionic

services:
    - docker

addons:
    apt:
        packages:
            - elinks
            - rsyslog

env:
    global:
        - GOPATH=/tmp/go
        - PATH=$GOPATH/bin:$PATH

cache:
    directories:
        - $HOME/.kerl

before_install:
    # install erlang/otp
    - curl -O https://raw.githubusercontent.com/kerl/kerl/master/kerl
    - chmod a+x kerl
    - travis_wait 30 ./kerl build 22.2
    - ./kerl install 22.2 ~/.kerl/22.2
    - . ~/.kerl/22.2/activate
    # get pebble docker-compose configuration
    - wget https://raw.githubusercontent.com/letsencrypt/pebble/master/docker-compose.yml
    # disable invalid anti-replay nonce random errors
    - "sed -ie 's/\\(GODEBUG:.*\\)/\\1\\n      PEBBLE_WFE_NONCEREJECT: 0/' docker-compose.yml"

install:
    - ./rebar3 update
    - DEBUG=1 ./rebar3 as test compile

before_script:
    - docker-compose -f docker-compose.yml up > /tmp/pebble.log&
    - sleep 10
    - curl --request POST --data '{"ip":"10.30.50.1"}' http://localhost:8055/set-default-ipv4

#
script:
    - make dialize
    - DEBUG=1 ./rebar3 ct > /tmp/ct.log 2>&1
#
after_failure:
    - cat /tmp/pebble.log
    - cat /tmp/ct.log
    - elinks -dump 1 _build/test/logs/ct_run.*/*/run.*/suite.log.html
    - elinks -dump 1 _build/test/logs/ct_run.*/*/run.*/letsencrypt_suite.test_*
    - elinks -dump 1 _build/test/logs/ct_run.*/*/run.*/unexpected_io.log.html
#
after_success:
    - elinks -dump 1 _build/test/logs/ct_run.*/*/run.*/suite.log.html
    - elinks -dump 1 _build/test/logs/ct_run.*/*/run.*/letsencrypt_suite.test_*
    - elinks -dump 1 _build/test/logs/ct_run.*/*/run.*/unexpected_io.log.html
    - cat /tmp/pebble.log
